CREATE TABLE IF NOT EXISTS monthly_snapshots (
    id BIGSERIAL PRIMARY KEY,
    snapshot_month VARCHAR(7) NOT NULL,
    snapshot_date DATE NOT NULL,
    entity VARCHAR(50) NOT NULL,
    active_clients INTEGER,
    active_contracts INTEGER,
    current_mrr NUMERIC,
    current_arr NUMERIC,
    future_mrr NUMERIC,
    future_arr NUMERIC,
    average_client_mrr NUMERIC,
    average_contract_length NUMERIC,
    average_contract_length_all_time NUMERIC,
    clv NUMERIC,
    churned_clients_ytd INTEGER,
    churned_mrr_ytd NUMERIC,
    churned_clients_last_year INTEGER,
    churned_mrr_last_year NUMERIC,
    new_contracts INTEGER,
    nrr_quarterly NUMERIC,
    grr_quarterly NUMERIC,
    cac NUMERIC,
    total_income NUMERIC,
    gross_profit NUMERIC,
    gross_margin NUMERIC,
    net_profit NUMERIC,
    net_profit_margin NUMERIC,
    ebitda NUMERIC,
    ebitda_margin NUMERIC,
    rule_of_40 NUMERIC,
    cash NUMERIC,
    debtor_days NUMERIC,
    creditor_days NUMERIC,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_monthly_snapshots_month_entity UNIQUE (snapshot_month, entity)
);
